namespace BotWhatsapp.Domain.Events;
public static class AppointmentEvents
{
    // Eventos de Creación
    public const string APPOINTMENT_CREATED = "APPOINTMENT_CREATED";
    public const string APPOINTMENT_CREATION_FAILED = "APPOINTMENT_CREATION_FAILED";
    public const string APPOINTMENT_CODE_GENERATED = "APPOINTMENT_CODE_GENERATED";
    
    // Eventos de Actualización
    public const string APPOINTMENT_UPDATED = "APPOINTMENT_UPDATED";
    public const string APPOINTMENT_UPDATE_FAILED = "APPOINTMENT_UPDATE_FAILED";
    public const string APPOINTMENT_CHANGED_DATE = "APPOINTMENT_CHANGED_DATE";
    public const string APPOINTMENT_CHANGED_TIME = "APPOINTMENT_CHANGED_TIME";
    public const string APPOINTMENT_CHANGED_SERVICE = "APPOINTMENT_CHANGED_SERVICE";
    public const string APPOINTMENT_CHANGED_RESOURCE = "APPOINTMENT_CHANGED_RESOURCE";
    public const string APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED";
    
    // Eventos de Estado
    public const string APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED";
    public const string APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED";
    public const string APPOINTMENT_COMPLETED = "APPOINTMENT_COMPLETED";
    public const string APPOINTMENT_NO_SHOW = "APPOINTMENT_NO_SHOW";
    public const string APPOINTMENT_IN_PROGRESS = "APPOINTMENT_IN_PROGRESS";
    public const string APPOINTMENT_PENDING = "APPOINTMENT_PENDING";
    
    // Eventos de Validación
    public const string APPOINTMENT_VALIDATION_FAILED = "APPOINTMENT_VALIDATION_FAILED";
    public const string APPOINTMENT_CLIENT_NOT_FOUND = "APPOINTMENT_CLIENT_NOT_FOUND";
    public const string APPOINTMENT_SERVICE_NOT_FOUND = "APPOINTMENT_SERVICE_NOT_FOUND";
    public const string APPOINTMENT_RESOURCE_NOT_FOUND = "APPOINTMENT_RESOURCE_NOT_FOUND";
    public const string APPOINTMENT_RESOURCE_UNAVAILABLE = "APPOINTMENT_RESOURCE_UNAVAILABLE";
    public const string APPOINTMENT_INVALID_DATE = "APPOINTMENT_INVALID_DATE";
    public const string APPOINTMENT_OUTSIDE_BUSINESS_HOURS = "APPOINTMENT_OUTSIDE_BUSINESS_HOURS";
    public const string APPOINTMENT_RESOURCE_NOT_QUALIFIED = "APPOINTMENT_RESOURCE_NOT_QUALIFIED";
    
    // Eventos de Recordatorios
    public const string APPOINTMENT_REMINDER_SCHEDULED = "APPOINTMENT_REMINDER_SCHEDULED";
    public const string APPOINTMENT_REMINDER_SENT = "APPOINTMENT_REMINDER_SENT";
    public const string APPOINTMENT_REMINDER_FAILED = "APPOINTMENT_REMINDER_FAILED";
    public const string APPOINTMENT_NOTIFICATION_SENT = "APPOINTMENT_NOTIFICATION_SENT";
    
    // Eventos de Disponibilidad
    public const string APPOINTMENT_AVAILABILITY_CHECKED = "APPOINTMENT_AVAILABILITY_CHECKED";
    public const string APPOINTMENT_SLOT_BLOCKED = "APPOINTMENT_SLOT_BLOCKED";
    public const string APPOINTMENT_SLOT_RELEASED = "APPOINTMENT_SLOT_RELEASED";
    
    // Eventos de Cliente
    public const string APPOINTMENT_CLIENT_ARRIVED = "APPOINTMENT_CLIENT_ARRIVED";
    public const string APPOINTMENT_CLIENT_LATE = "APPOINTMENT_CLIENT_LATE";
    public const string APPOINTMENT_CLIENT_EARLY = "APPOINTMENT_CLIENT_EARLY";
    
    // Eventos de Sistema
    public const string APPOINTMENT_VIEWED = "APPOINTMENT_VIEWED";
    public const string APPOINTMENT_SEARCHED = "APPOINTMENT_SEARCHED";
    public const string APPOINTMENT_EXPORTED = "APPOINTMENT_EXPORTED";
    public const string APPOINTMENT_IMPORTED = "APPOINTMENT_IMPORTED";
    
    // Eventos de WhatsApp Bot
    public const string APPOINTMENT_REQUESTED_VIA_BOT = "APPOINTMENT_REQUESTED_VIA_BOT";
    public const string APPOINTMENT_CONFIRMED_VIA_BOT = "APPOINTMENT_CONFIRMED_VIA_BOT";
    public const string APPOINTMENT_CANCELLED_VIA_BOT = "APPOINTMENT_CANCELLED_VIA_BOT";
    public const string APPOINTMENT_RESCHEDULED_VIA_BOT = "APPOINTMENT_RESCHEDULED_VIA_BOT";
    
    // Eventos de Errores
    public const string APPOINTMENT_ERROR_OCCURRED = "APPOINTMENT_ERROR_OCCURRED";
    public const string APPOINTMENT_CONFLICT_DETECTED = "APPOINTMENT_CONFLICT_DETECTED";
    public const string APPOINTMENT_DUPLICATE_DETECTED = "APPOINTMENT_DUPLICATE_DETECTED";
    
    // Eventos de Auditoría
    public const string APPOINTMENT_ACCESSED_BY_USER = "APPOINTMENT_ACCESSED_BY_USER";
    public const string APPOINTMENT_MODIFIED_BY_ADMIN = "APPOINTMENT_MODIFIED_BY_ADMIN";
    public const string APPOINTMENT_DELETED_BY_ADMIN = "APPOINTMENT_DELETED_BY_ADMIN";
}